name: aioverflow-dev

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - ConnectionString=Host=db;Database=forumdb;Username=forumadmin;Password=securepassword
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_APPLICATIONNAME=AIOverflow
    networks:
      - forum-network
    profiles:
      ["web"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: forumdb
      POSTGRES_USER: forumadmin
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - forum-network
    profiles:
      ["db"]

volumes:
  pgdata:

networks:
  forum-network:
    driver: bridge