CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "PasswordHash" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "UserClaim" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" text NOT NULL,
    "Value" text NOT NULL,
    "UserId" integer NULL,
    CONSTRAINT "PK_UserClaim" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaim_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE INDEX "IX_UserClaim_UserId" ON "UserClaim" ("UserId");

CREATE UNIQUE INDEX "IX_Users_Name" ON "Users" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231230234355_InitialCreate', '7.0.14');

COMMIT;

